apiVersion: apps/v1
kind: Deployment
metadata:
    name: myapp-deploy
    labels:
      app: myapp
spec:
    replicas: 3
    selector: 
      matchLabels: 
        app: myapp
    template:
      metadata: 
        labels:
          app: myapp
      spec:
        containers: 
        - name: myapp-pod
          image: shreyanshishukla/bootimage5
          ports:
          - containerPort: 9595


