apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9595
  type: NodePort











